libbtc: /Users/jonasschnelli/Documents/bitcoin/libbtc/src/aes.h File Reference
aes.h File Reference
Data Structures
struct aes_context
Macros
#define AES_ENC_PREKEYED /* AES encryption with a precomputed key schedule */
#define AES_DEC_PREKEYED /* AES decryption with a precomputed key schedule */
#define N_ROW 4
#define N_COL 4
#define N_BLOCK (N_ROW * N_COL)
#define N_MAX_ROUNDS 14
Typedefs
typedef unsigned char uint_8t
typedef uint_8t return_type
typedef uint_8t length_type
Functions
return_type aes_set_key (const unsigned char key[], length_type keylen, aes_context ctx[1])
return_type aes_encrypt (const unsigned char in[N_BLOCK], unsigned char out[N_BLOCK], const aes_context ctx[1])
return_type aes_cbc_encrypt (const unsigned char *in, unsigned char *out, int n_block, unsigned char iv[N_BLOCK], const aes_context ctx[1])
return_type aes_decrypt (const unsigned char in[N_BLOCK], unsigned char out[N_BLOCK], const aes_context ctx[1])
return_type aes_cbc_decrypt (const unsigned char *in, unsigned char *out, int n_block, unsigned char iv[N_BLOCK], const aes_context ctx[1])
Macro Definition Documentation
#define AES_DEC_PREKEYED /* AES decryption with a precomputed key schedule */
Definition at line 43 of file aes.h.
#define AES_ENC_PREKEYED /* AES encryption with a precomputed key schedule */
Definition at line 40 of file aes.h.
#define N_BLOCK (N_ROW * N_COL)
Definition at line 60 of file aes.h.
Referenced by aes_cbc_decrypt(), aes_cbc_encrypt(), aes_decrypt(), aes_encrypt(), inv_mix_sub_columns(), and mix_sub_columns().
#define N_COL 4
Definition at line 59 of file aes.h.
#define N_MAX_ROUNDS 14
Definition at line 61 of file aes.h.
#define N_ROW 4
Definition at line 58 of file aes.h.
Typedef Documentation
typedef uint_8t length_type
Definition at line 71 of file aes.h.
typedef uint_8t return_type
Definition at line 65 of file aes.h.
typedef unsigned char uint_8t
Definition at line 63 of file aes.h.
Function Documentation
return_type aes_cbc_decrypt (const unsigned char * in, unsigned char * out, int n_block, unsigned char iv[N_BLOCK], const aes_context ctx[1])
Definition at line 586 of file aes.c.
References aes_decrypt(), N_BLOCK, and xor_block().
 {
     while (n_block--) {
         uint_8t tmp[N_BLOCK];
         memcpy(tmp, in, N_BLOCK);
         if (aes_decrypt(in, out, ctx) != EXIT_SUCCESS) {
             return EXIT_FAILURE;
         }
         xor_block(out, iv);
         memcpy(iv, tmp, N_BLOCK);
         in += N_BLOCK;
         out += N_BLOCK;
     }
     return EXIT_SUCCESS;
 }
return_type aes_cbc_encrypt (const unsigned char * in, unsigned char * out, int n_block, unsigned char iv[N_BLOCK], const aes_context ctx[1])
Definition at line 537 of file aes.c.
References aes_encrypt(), N_BLOCK, and xor_block().
 {
     while (n_block--) {
         xor_block(iv, in);
         if (aes_encrypt(iv, iv, ctx) != EXIT_SUCCESS) {
             return EXIT_FAILURE;
         }
         memcpy(out, iv, N_BLOCK);
         in += N_BLOCK;
         out += N_BLOCK;
     }
     return EXIT_SUCCESS;
 }
return_type aes_decrypt (const unsigned char in[N_BLOCK], unsigned char out[N_BLOCK], const aes_context ctx[1])
Definition at line 557 of file aes.c.
References add_round_key(), copy_and_key(), inv_mix_sub_columns(), inv_shift_sub_rows(), aes_context::ksch, N_BLOCK, and aes_context::rnd.
Referenced by aes_cbc_decrypt().
 {
     if (ctx->rnd) {
         uint_8t s1[N_BLOCK], r;
         copy_and_key(s1, in, ctx->ksch + ctx->rnd * N_BLOCK);
         inv_shift_sub_rows(s1);
         for (r = ctx->rnd; --r;)
 #if defined(VERSION_1)
         {
             add_round_key(s1, ctx->ksch + r * N_BLOCK);
             inv_mix_sub_columns(s1);
         }
 #else
         {
             uint_8t s2[N_BLOCK];
             copy_and_key(s2, s1, ctx->ksch + r * N_BLOCK);
             inv_mix_sub_columns(s1, s2);
         }
 #endif
         copy_and_key(out, s1, ctx->ksch);
     } else {
         return -1;
     }
     return 0;
 }
return_type aes_encrypt (const unsigned char in[N_BLOCK], unsigned char out[N_BLOCK], const aes_context ctx[1])
Definition at line 508 of file aes.c.
References add_round_key(), copy_and_key(), aes_context::ksch, mix_sub_columns(), N_BLOCK, aes_context::rnd, shift_sub_rows(), and VERSION_1.
Referenced by aes_cbc_encrypt().
 {
     if (ctx->rnd) {
         uint_8t s1[N_BLOCK], r;
         copy_and_key(s1, in, ctx->ksch);
         for (r = 1; r < ctx->rnd; ++r)
 #if defined(VERSION_1)
         {
             mix_sub_columns(s1);
             add_round_key(s1, ctx->ksch + r * N_BLOCK);
         }
 #else
         {
             uint_8t s2[N_BLOCK];
             mix_sub_columns(s2, s1);
             copy_and_key(s1, s2, ctx->ksch + r * N_BLOCK);
         }
 #endif
         shift_sub_rows(s1);
         copy_and_key(out, s1, ctx->ksch + r * N_BLOCK);
     } else {
         return -1;
     }
     return 0;
 }
return_type aes_set_key (const unsigned char key[], length_type keylen, aes_context ctx[1])
Definition at line 449 of file aes.c.
References block_copy_nn, f2, aes_context::ksch, aes_context::rnd, and s_box.
 {
     uint_8t cc, rc, hi;
     switch (keylen) {
     case 16:
     case 128:
         keylen = 16;
         break;
     case 24:
     case 192:
         keylen = 24;
         break;
     case 32:
         //case 256:
         keylen = 32;
         break;
     default:
         ctx->rnd = 0;
         return -1;
     }
     block_copy_nn(ctx->ksch, key, keylen);
     hi = (keylen + 28) << 2;
     ctx->rnd = (hi >> 4) - 1;
     for (cc = keylen, rc = 1; cc < hi; cc += 4) {
         uint_8t tt, t0, t1, t2, t3;
         t0 = ctx->ksch[cc - 4];
         t1 = ctx->ksch[cc - 3];
         t2 = ctx->ksch[cc - 2];
         t3 = ctx->ksch[cc - 1];
         if (cc % keylen == 0) {
             tt = t0;
             t0 = s_box(t1) ^ rc;
             t1 = s_box(t2);
             t2 = s_box(t3);
             t3 = s_box(tt);
             rc = f2(rc);
         } else if (keylen > 24 && cc % keylen == 16) {
             t0 = s_box(t0);
             t1 = s_box(t1);
             t2 = s_box(t2);
             t3 = s_box(t3);
         }
         tt = cc - keylen;
         ctx->ksch[cc + 0] = ctx->ksch[tt + 0] ^ t0;
         ctx->ksch[cc + 1] = ctx->ksch[tt + 1] ^ t1;
         ctx->ksch[cc + 2] = ctx->ksch[tt + 2] ^ t2;
         ctx->ksch[cc + 3] = ctx->ksch[tt + 3] ^ t3;
     }
     return 0;
 }