libbtc: /Users/jonasschnelli/Documents/bitcoin/libbtc/src/cstr.c File Reference
cstr.c File Reference
#include "btc/cstr.h"
#include <string.h>
Functions
static btc_bool cstr_alloc_min_sz (cstring *s, size_t sz)
cstring * cstr_new_sz (size_t sz)
cstring * cstr_new_buf (const void *buf, size_t sz)
cstring * cstr_new (const char *init_str)
void cstr_free (cstring *s, btc_bool free_buf)
btc_bool cstr_resize (cstring *s, size_t new_sz)
btc_bool cstr_append_buf (cstring *s, const void *buf, size_t sz)
btc_bool cstr_equal (const cstring *a, const cstring *b)
btc_bool cstr_erase (cstring *s, size_t pos, ssize_t len)
Function Documentation
static btc_bool cstr_alloc_min_sz (cstring * s, size_t sz) static
Definition at line 10 of file cstr.c.
References cstring::alloc, cstring::len, and cstring::str.
Referenced by cstr_append_buf(), cstr_new_sz(), and cstr_resize().
 {
     sz++; // NUL overhead
     if (s->alloc && (s->alloc >= sz))
         return true;
     unsigned int shift = 3;
     unsigned int al_sz;
     while ((al_sz = (1 << shift)) < sz)
         shift++;
     char* new_s = realloc(s->str, al_sz);
     if (!new_s)
         return false;
     s->str = new_s;
     s->alloc = al_sz;
     s->str[s->len] = 0;
     return true;
 }
btc_bool cstr_append_buf (cstring * s, const void * buf, size_t sz)
Definition at line 106 of file cstr.c.
References cstr_alloc_min_sz(), cstring::len, and cstring::str.
Referenced by btc_script_append_op(), btc_script_append_pushdata(), btc_script_build_multisig(), btc_script_copy_without_op_codeseperator(), btc_tx_in_copy(), btc_tx_out_copy(), btc_tx_sighash(), cstr_append_c(), deser_varstr(), ser_bytes(), ser_u16(), ser_u32(), and ser_u64().
 {
     if (!cstr_alloc_min_sz(s, s->len + sz))
         return false;
     memcpy(s->str + s->len, buf, sz);
     s->len += sz;
     s->str[s->len] = 0;
     return true;
 }
btc_bool cstr_equal (const cstring * a, const cstring * b)
Definition at line 118 of file cstr.c.
References cstring::len, and cstring::str.
 {
     if (a == b)
         return true;
     if (!a || !b)
         return false;
     if (a->len != b->len)
         return false;
     return (memcmp(a->str, b->str, a->len) == 0);
 }
btc_bool cstr_erase (cstring * s, size_t pos, ssize_t len)
Definition at line 129 of file cstr.c.
References buffer::len, cstring::len, and cstring::str.
 {
     if (pos == s->len && len == 0)
         return true;
     if (pos >= s->len)
         return false;
     ssize_t old_tail = s->len - pos;
     if ((len >= 0) && (len > old_tail))
         return false;
     memmove(&s->str[pos], &s->str[pos + len], old_tail - len);
     s->len -= len;
     s->str[s->len] = 0;
     return true;
 }
void cstr_free (cstring * s, btc_bool free_buf)
Definition at line 69 of file cstr.c.
References cstring::str.
Referenced by btc_tx_hash(), btc_tx_in_free(), btc_tx_out_free(), btc_tx_sighash(), and deser_varstr().
 {
     if (!s)
         return;
     if (free_buf)
         free(s->str);
     memset(s, 0, sizeof(*s));
     free(s);
 }
cstring* cstr_new (const char * init_str)
Definition at line 60 of file cstr.c.
References cstr_new_buf(), and cstr_new_sz().
 {
     if (!init_str || !*init_str)
         return cstr_new_sz(0);
     size_t slen = strlen(init_str);
     return cstr_new_buf(init_str, slen);
 }
cstring* cstr_new_buf (const void * buf, size_t sz)
Definition at line 47 of file cstr.c.
References cstr_new_sz(), cstring::len, and cstring::str.
Referenced by cstr_new().
 {
     cstring* s = cstr_new_sz(sz);
     if (!s)
         return NULL;
     memcpy(s->str, buf, sz);
     s->len = sz;
     s->str[s->len] = 0;
     return s;
 }
cstring* cstr_new_sz (size_t sz)
Definition at line 33 of file cstr.c.
References cstr_alloc_min_sz().
Referenced by btc_tx_add_p2pkh_hash160_out(), btc_tx_add_p2sh_hash160_out(), btc_tx_hash(), btc_tx_in_copy(), btc_tx_out_copy(), btc_tx_sighash(), cstr_new(), cstr_new_buf(), and deser_varstr().
 {
     cstring* s = calloc(1, sizeof(cstring));
     if (!s)
         return NULL;
     if (!cstr_alloc_min_sz(s, sz)) {
         free(s);
         return NULL;
     }
     return s;
 }
btc_bool cstr_resize (cstring * s, size_t new_sz)
Definition at line 81 of file cstr.c.
References cstr_alloc_min_sz(), buffer::len, cstring::len, and cstring::str.
Referenced by btc_script_build_multisig(), btc_script_build_p2pkh(), btc_script_build_p2sh(), and btc_tx_sighash().
 {
     // no change
     if (new_sz == s->len)
         return true;
     // truncate string
     if (new_sz <= s->len) {
         s->len = new_sz;
         s->str[s->len] = 0;
         return true;
     }
     // increase string size
     if (!cstr_alloc_min_sz(s, new_sz))
         return false;
     // contents of string tail undefined
     s->len = new_sz;
     s->str[s->len] = 0;
     return true;
 }