libbtc: /Users/jonasschnelli/Documents/bitcoin/libbtc/src/ecc_libsecp256k1.c File Reference
ecc_libsecp256k1.c File Reference
#include "secp256k1/include/secp256k1.h"
#include <assert.h>
#include <stdint.h>
#include <string.h>
#include "btc/btc.h"
#include "random.h"
Functions
void ecc_start (void)
init static ecc context
void ecc_stop (void)
destroys the static ecc context
void ecc_get_pubkey (const uint8_t *private_key, uint8_t *public_key, size_t *in_outlen, btc_bool compressed)
get public key from given private key
btc_bool ecc_private_key_tweak_add (uint8_t *private_key, const uint8_t *tweak)
ec mul tweak on given private key
btc_bool ecc_public_key_tweak_add (uint8_t *public_key_inout, const uint8_t *tweak)
ec mul tweak on given public key
btc_bool ecc_verify_privatekey (const uint8_t *private_key)
verifies a given 32byte key
btc_bool ecc_verify_pubkey (const uint8_t *public_key, btc_bool compressed)
verifies a given public key (compressed[33] or uncompressed[65] bytes)
btc_bool ecc_sign (const uint8_t *private_key, const uint8_t *hash, unsigned char *sigder, size_t *outlen)
btc_bool ecc_verify_sig (const uint8_t *public_key, btc_bool compressed, const uint8_t *hash, unsigned char *sigder, size_t siglen)
Variables
static secp256k1_context * secp256k1_ctx = NULL
Function Documentation
void ecc_get_pubkey (const uint8_t * private_key, uint8_t * public_key, size_t * in_outlen, btc_bool compressed)
get public key from given private key
Definition at line 36 of file ecc_libsecp256k1.c.
References secp256k1_ctx.
Referenced by btc_hdnode_fill_public_key(), and btc_pubkey_from_key().
 {
     secp256k1_pubkey pubkey;
     assert(secp256k1_ctx);
     assert((int)*in_outlen == (compressed ? 33 : 65));
     memset(public_key, 0, *in_outlen);
     if (!secp256k1_ec_pubkey_create(secp256k1_ctx, &pubkey, (const unsigned char*)private_key)) {
         return;
     }
     if (!secp256k1_ec_pubkey_serialize(secp256k1_ctx, public_key, in_outlen, &pubkey, compressed)) {
         return;
     }
     return;
 }
btc_bool ecc_private_key_tweak_add (uint8_t * private_key, const uint8_t * tweak)
ec mul tweak on given private key
Definition at line 54 of file ecc_libsecp256k1.c.
References secp256k1_ctx.
Referenced by btc_hdnode_private_ckd().
 {
     assert(secp256k1_ctx);
     return secp256k1_ec_privkey_tweak_add(secp256k1_ctx, (unsigned char*)private_key, (const unsigned char*)tweak);
 }
btc_bool ecc_public_key_tweak_add (uint8_t * public_key_inout, const uint8_t * tweak)
ec mul tweak on given public key
Definition at line 60 of file ecc_libsecp256k1.c.
References secp256k1_ctx.
Referenced by btc_hdnode_public_ckd().
 {
     size_t out;
     secp256k1_pubkey pubkey;
     assert(secp256k1_ctx);
     if (!secp256k1_ec_pubkey_parse(secp256k1_ctx, &pubkey, public_key_inout, 33))
         return false;
     if (!secp256k1_ec_pubkey_tweak_add(secp256k1_ctx, &pubkey, (const unsigned char*)tweak))
         return false;
     if (!secp256k1_ec_pubkey_serialize(secp256k1_ctx, public_key_inout, &out, &pubkey, SECP256K1_EC_COMPRESSED))
         return false;
     return true;
 }
btc_bool ecc_sign (const uint8_t * private_key, const uint8_t * hash, unsigned char * sigder, size_t * outlen)
Definition at line 99 of file ecc_libsecp256k1.c.
References secp256k1_ctx.
Referenced by btc_key_sign_hash().
 {
     assert(secp256k1_ctx);
     secp256k1_ecdsa_signature sig;
     if (!secp256k1_ecdsa_sign(secp256k1_ctx, &sig, hash, private_key, secp256k1_nonce_function_rfc6979, NULL))
         return 0;
     if (!secp256k1_ecdsa_signature_serialize_der(secp256k1_ctx, sigder, outlen, &sig))
         return 0;
     return 1;
 }
void ecc_start (void)
init static ecc context
Definition at line 13 of file ecc_libsecp256k1.c.
References random_bytes(), and secp256k1_ctx.
 {
     secp256k1_ctx = secp256k1_context_create(SECP256K1_CONTEXT_SIGN | SECP256K1_CONTEXT_VERIFY);
     assert(secp256k1_ctx != NULL);
     uint8_t seed[32];
     random_bytes(seed, 32, 0);
     int ret = secp256k1_context_randomize(secp256k1_ctx, seed);
     assert(ret);
 }
void ecc_stop (void)
destroys the static ecc context
Definition at line 25 of file ecc_libsecp256k1.c.
References secp256k1_ctx.
 {
     secp256k1_context* ctx = secp256k1_ctx;
     secp256k1_ctx = NULL;
     if (ctx) {
         secp256k1_context_destroy(ctx);
     }
 }
btc_bool ecc_verify_privatekey (const uint8_t * private_key)
verifies a given 32byte key
Definition at line 79 of file ecc_libsecp256k1.c.
References secp256k1_ctx.
Referenced by btc_hdnode_from_seed(), btc_hdnode_private_ckd(), btc_privkey_gen(), and btc_privkey_is_valid().
 {
     assert(secp256k1_ctx);
     return secp256k1_ec_seckey_verify(secp256k1_ctx, (const unsigned char*)private_key);
 }
btc_bool ecc_verify_pubkey (const uint8_t * public_key, btc_bool compressed)
verifies a given public key (compressed[33] or uncompressed[65] bytes)
Definition at line 85 of file ecc_libsecp256k1.c.
References secp256k1_ctx.
Referenced by btc_pubkey_is_valid().
 {
     secp256k1_pubkey pubkey;
     assert(secp256k1_ctx);
     if (!secp256k1_ec_pubkey_parse(secp256k1_ctx, &pubkey, public_key, compressed ? 33 : 65)) {
         memset(&pubkey, 0, sizeof(pubkey));
         return false;
     }
     memset(&pubkey, 0, sizeof(pubkey));
     return true;
 }
btc_bool ecc_verify_sig (const uint8_t * public_key, btc_bool compressed, const uint8_t * hash, unsigned char * sigder, size_t siglen)
Definition at line 113 of file ecc_libsecp256k1.c.
References secp256k1_ctx.
Referenced by btc_pubkey_verify_sig().
 {
     assert(secp256k1_ctx);
     secp256k1_ecdsa_signature sig;
     secp256k1_pubkey pubkey;
     if (!secp256k1_ec_pubkey_parse(secp256k1_ctx, &pubkey, public_key, compressed ? 33 : 65))
         return false;
     if (!secp256k1_ecdsa_signature_parse_der(secp256k1_ctx, &sig, sigder, siglen))
         return false;
     return secp256k1_ecdsa_verify(secp256k1_ctx, &sig, hash, &pubkey);
 }
Variable Documentation
secp256k1_context* secp256k1_ctx = NULL static
Definition at line 11 of file ecc_libsecp256k1.c.
Referenced by ecc_get_pubkey(), ecc_private_key_tweak_add(), ecc_public_key_tweak_add(), ecc_sign(), ecc_start(), ecc_stop(), ecc_verify_privatekey(), ecc_verify_pubkey(), and ecc_verify_sig().