libbtc: /Users/jonasschnelli/Documents/bitcoin/libbtc/include/btc/hash.h File Reference
hash.h File Reference
#include "btc.h"
#include <stdint.h>
#include <stddef.h>
#include "cstr.h"
#include "vector.h"
Typedefs
typedef uint8_t uint256[32]
Functions
LIBBTC_API void btc_hash (const unsigned char *datain, size_t length, uint256 hashout)
LIBBTC_API void btc_hash_sngl_sha256 (const unsigned char *datain, size_t length, uint256 hashout)
Typedef Documentation
typedef uint8_t uint256[32]
Definition at line 44 of file hash.h.
Function Documentation
LIBBTC_API void btc_hash (const unsigned char * datain, size_t length, uint256 hashout)
Definition at line 1026 of file sha2.c.
References sha256_Raw().
Referenced by btc_privkey_verify_pubkey().
 {
     //bitcoin double sha256 hash
     sha256_Raw((const uint8_t*)datain, length, hashout);
     sha256_Raw(hashout, 32, hashout);
 }
LIBBTC_API void btc_hash_sngl_sha256 (const unsigned char * datain, size_t length, uint256 hashout)
Definition at line 1033 of file sha2.c.
References sha256_Raw().
 {
     sha256_Raw((const uint8_t*)datain, length, hashout);
 }