libbtc: /Users/jonasschnelli/Documents/bitcoin/libbtc/src/random.h File Reference
random.h File Reference
#include <stdint.h>
#include <stdlib.h>
#include "btc/btc.h"
Functions
void random_init (void)
btc_bool random_bytes (uint8_t *buf, uint32_t len, const uint8_t update_seed)
Function Documentation
btc_bool random_bytes (uint8_t * buf, uint32_t len, const uint8_t update_seed)
Definition at line 57 of file random.c.
References RANDOM_DEVICE.
Referenced by btc_privkey_gen(), btc_privkey_verify_pubkey(), and ecc_start().
 {
     (void)update_seed; //unused
     FILE* frand = fopen(RANDOM_DEVICE, "r");
     if (!frand) {
         return false;
     }
     size_t len_read = fread(buf, 1, len, frand);
     assert(len_read == len);
     fclose(frand);
     return true;
 }
void random_init (void)
Definition at line 54 of file random.c.
 {}