libbtc: /Users/jonasschnelli/Documents/bitcoin/libbtc/src/script.c File Reference
script.c File Reference
#include <btc/script.h>
#include <assert.h>
#include <string.h>
#include "buffer.h"
#include "serialize.h"
Functions
btc_bool btc_script_copy_without_op_codeseperator (const cstring *script_in, cstring *script_out)
btc_script_op * btc_script_op_new ()
void btc_script_op_free (btc_script_op *script_op)
void btc_script_op_free_cb (void *data)
btc_bool btc_script_get_ops (const cstring *script_in, vector *ops_out)
static btc_bool btc_script_is_pushdata (enum opcodetype op)
static btc_bool btc_script_is_op (const btc_script_op *op, enum opcodetype opcode)
static btc_bool btc_script_is_op_pubkey (const btc_script_op *op)
static btc_bool btc_script_is_op_pubkeyhash (const btc_script_op *op)
btc_bool btc_script_is_pubkey (vector *ops)
btc_bool btc_script_is_pubkeyhash (vector *ops)
btc_bool btc_script_is_scripthash (vector *ops)
static btc_bool btc_script_is_op_smallint (const btc_script_op *op)
btc_bool btc_script_is_multisig (vector *ops)
enum btc_tx_out_type btc_script_classify (vector *ops)
static enum opcodetype btc_encode_op_n (int n)
static void btc_script_append_op (cstring *script_in, enum opcodetype op)
static void btc_script_append_pushdata (cstring *script_in, unsigned char *data, size_t datalen)
btc_bool btc_script_build_multisig (cstring *script_in, unsigned int required_signatures, vector *pubkeys_chars)
btc_bool btc_script_build_p2pkh (cstring *script_in, const uint8_t *hash160)
btc_bool btc_script_build_p2sh (cstring *script_in, const uint8_t *hash160)
Function Documentation
static enum opcodetype btc_encode_op_n (int n) static
Definition at line 257 of file script.c.
References OP_0, and OP_1.
Referenced by btc_script_build_multisig().
 {
     assert(n >= 0 && n <= 16);
     if (n == 0)
         return OP_0;
     return (enum opcodetype)(OP_1+n-1);
 }
static void btc_script_append_op (cstring * script_in, enum opcodetype op) static
Definition at line 266 of file script.c.
References cstr_append_buf().
Referenced by btc_script_append_pushdata(), btc_script_build_p2pkh(), and btc_script_build_p2sh().
 {
     cstr_append_buf(script_in, &op, 1);
 }
static void btc_script_append_pushdata (cstring * script_in, unsigned char * data, size_t datalen) static
Definition at line 272 of file script.c.
References btc_script_append_op(), cstr_append_buf(), OP_PUSHDATA1, OP_PUSHDATA2, and OP_PUSHDATA4.
Referenced by btc_script_build_multisig(), btc_script_build_p2pkh(), and btc_script_build_p2sh().
 {
     if (datalen < OP_PUSHDATA1)
     {
         cstr_append_buf(script_in, (unsigned char *)&datalen, 1);
     }
     else if (datalen <= 0xff)
     {
         btc_script_append_op(script_in, OP_PUSHDATA1);
         cstr_append_buf(script_in, (unsigned char *)&datalen, 1);
     }
     else if (datalen <= 0xffff)
     {
         btc_script_append_op(script_in, OP_PUSHDATA2);
         uint16_t v = htole16(datalen);
         cstr_append_buf(script_in, &v, sizeof(v));
     }
     else
     {
         btc_script_append_op(script_in, OP_PUSHDATA4);
         uint32_t v = htole32(datalen);
         cstr_append_buf(script_in, &v, sizeof(v));
     }
     cstr_append_buf(script_in, data, datalen);
 }
btc_bool btc_script_build_multisig (cstring * script_in, unsigned int required_signatures, vector * pubkeys_chars)
Definition at line 298 of file script.c.
References BTC_ECKEY_COMPRESSED_LENGTH, BTC_ECKEY_UNCOMPRESSED_LENGTH, btc_encode_op_n(), btc_script_append_pushdata(), btc_pubkey_::compressed, cstr_append_buf(), cstr_resize(), vector::data, vector::len, OP_CHECKMULTISIG, and btc_pubkey_::pubkey.
 {
     cstr_resize(script_in, 0); //clear script
     if(required_signatures > 16 || pubkeys_chars->len > 16)
         return false;
     enum opcodetype op_req_sig = btc_encode_op_n(required_signatures);
     cstr_append_buf(script_in, &op_req_sig, 1);
     int i;
     for (i = 0; i < (int)pubkeys_chars->len; i++)
     {
         btc_pubkey *pkey = pubkeys_chars->data[i];
         btc_script_append_pushdata(script_in, pkey->pubkey, (pkey->compressed ? BTC_ECKEY_COMPRESSED_LENGTH : BTC_ECKEY_UNCOMPRESSED_LENGTH));
     }
     enum opcodetype op_pub_len = btc_encode_op_n(pubkeys_chars->len);
     cstr_append_buf(script_in, &op_pub_len, 1);
     enum opcodetype op_checkmultisig = OP_CHECKMULTISIG;
     cstr_append_buf(script_in, &op_checkmultisig, 1);
     return true;
 }
btc_bool btc_script_build_p2pkh (cstring * script_in, const uint8_t * hash160)
Definition at line 323 of file script.c.
References btc_script_append_op(), btc_script_append_pushdata(), cstr_resize(), OP_CHECKSIG, OP_DUP, OP_EQUALVERIFY, and OP_HASH160.
Referenced by btc_tx_add_p2pkh_hash160_out().
 {
     cstr_resize(script_in, 0); //clear script
     btc_script_append_op(script_in, OP_DUP);
     btc_script_append_op(script_in, OP_HASH160);
     btc_script_append_pushdata(script_in, hash160, 20);
     btc_script_append_op(script_in, OP_EQUALVERIFY);
     btc_script_append_op(script_in, OP_CHECKSIG);
     return true;
 }
btc_bool btc_script_build_p2sh (cstring * script_in, const uint8_t * hash160)
Definition at line 338 of file script.c.
References btc_script_append_op(), btc_script_append_pushdata(), cstr_resize(), OP_EQUAL, and OP_HASH160.
Referenced by btc_tx_add_p2sh_hash160_out().
 {
     cstr_resize(script_in, 0); //clear script
     btc_script_append_op(script_in, OP_HASH160);
     btc_script_append_pushdata(script_in, hash160, 20);
     btc_script_append_op(script_in, OP_EQUAL);
     return true;
 }
enum btc_tx_out_type btc_script_classify (vector * ops)
Definition at line 243 of file script.c.
References btc_script_is_multisig(), btc_script_is_pubkey(), btc_script_is_pubkeyhash(), btc_script_is_scripthash(), BTC_TX_MULTISIG, BTC_TX_NONSTANDARD, BTC_TX_PUBKEY, BTC_TX_PUBKEYHASH, and BTC_TX_SCRIPTHASH.
 {
     if (btc_script_is_pubkeyhash(ops))
         return BTC_TX_PUBKEYHASH;
     if (btc_script_is_scripthash(ops))
         return BTC_TX_SCRIPTHASH;
     if (btc_script_is_pubkey(ops))
         return BTC_TX_PUBKEY;
     if (btc_script_is_multisig(ops))
         return BTC_TX_MULTISIG;
     return BTC_TX_NONSTANDARD;
 }
btc_bool btc_script_copy_without_op_codeseperator (const cstring * script_in, cstring * script_out)
Definition at line 36 of file script.c.
References cstr_append_buf(), deser_bytes(), deser_skip(), deser_u16(), deser_u32(), const_buffer::len, cstring::len, OP_CODESEPARATOR, OP_PUSHDATA1, OP_PUSHDATA2, OP_PUSHDATA4, const_buffer::p, and cstring::str.
Referenced by btc_tx_sighash().
 {
     if (script_in->len == 0)
         return false; /* EOF */
     struct const_buffer buf = {script_in->str, script_in->len};
     unsigned char opcode;
     while (buf.len > 0) {
         if (!deser_bytes(&opcode, &buf, 1))
             goto err_out;
         uint32_t data_len;
         if (opcode == OP_CODESEPARATOR)
             continue;
         else if (opcode == OP_PUSHDATA1) {
             uint8_t v8;
             if (!deser_bytes(&v8, &buf, 1))
                 goto err_out;
             data_len = v8;
         } else if (opcode == OP_PUSHDATA2) {
             uint16_t v16;
             if (!deser_u16(&v16, &buf))
                 goto err_out;
             data_len = v16;
         } else if (opcode == OP_PUSHDATA4) {
             uint32_t v32;
             if (!deser_u32(&v32, &buf))
                 goto err_out;
             data_len = v32;
         } else {
             cstr_append_buf(script_out, &opcode, 1);
             continue;
         }
         cstr_append_buf(script_out, buf.p, data_len);
         if (!deser_skip(&buf, data_len))
             goto err_out;
     }
 err_out:
     return false;
 }
btc_bool btc_script_get_ops (const cstring * script_in, vector * ops_out)
Definition at line 108 of file script.c.
References btc_script_op_free(), btc_script_op_new(), btc_script_op_::data, btc_script_op_::datalen, deser_bytes(), deser_skip(), deser_u16(), deser_u32(), const_buffer::len, cstring::len, btc_script_op_::op, OP_PUSHDATA1, OP_PUSHDATA2, OP_PUSHDATA4, const_buffer::p, cstring::str, and vector_add().
 {
     if (script_in->len == 0)
         return false; /* EOF */
     struct const_buffer buf = {script_in->str, script_in->len};
     unsigned char opcode;
     btc_script_op* op = NULL;
     while (buf.len > 0) {
         op = btc_script_op_new();
         if (!deser_bytes(&opcode, &buf, 1))
             goto err_out;
         op->op = opcode;
         uint32_t data_len;
         if (opcode < OP_PUSHDATA1) {
             data_len = opcode;
         } else if (opcode == OP_PUSHDATA1) {
             uint8_t v8;
             if (!deser_bytes(&v8, &buf, 1))
                 goto err_out;
             data_len = v8;
         } else if (opcode == OP_PUSHDATA2) {
             uint16_t v16;
             if (!deser_u16(&v16, &buf))
                 goto err_out;
             data_len = v16;
         } else if (opcode == OP_PUSHDATA4) {
             uint32_t v32;
             if (!deser_u32(&v32, &buf))
                 goto err_out;
             data_len = v32;
         } else {
             vector_add(ops_out, op);
             continue;
         }
         op->data = calloc(1, data_len);
         memcpy(op->data, &buf.p, data_len);
         op->datalen = data_len;
         vector_add(ops_out, op);
         if (!deser_skip(&buf, data_len))
             goto err_out;
     }
     return true;
 err_out:
     btc_script_op_free(op);
     return false;
 }
btc_bool btc_script_is_multisig (vector * ops)
Definition at line 227 of file script.c.
References btc_script_is_op(), btc_script_is_op_pubkey(), btc_script_is_op_smallint(), vector::len, OP_CHECKMULTISIG, and vector_idx.
Referenced by btc_script_classify().
 {
     if ((ops->len < 3) || (ops->len > (16 + 3)) ||
         !btc_script_is_op_smallint(vector_idx(ops, 0)) ||
         !btc_script_is_op_smallint(vector_idx(ops, ops->len - 2)) ||
         !btc_script_is_op(vector_idx(ops, ops->len - 1), OP_CHECKMULTISIG))
         return false;
     unsigned int i;
     for (i = 1; i < (ops->len - 2); i++)
         if (!btc_script_is_op_pubkey(vector_idx(ops, i)))
             return false;
     return true;
 }
static btc_bool btc_script_is_op (const btc_script_op * op, enum opcodetype opcode) static
Definition at line 170 of file script.c.
References btc_script_op_::op.
Referenced by btc_script_is_multisig(), btc_script_is_pubkey(), btc_script_is_pubkeyhash(), and btc_script_is_scripthash().
 {
     return (op->op == opcode);
 }
static btc_bool btc_script_is_op_pubkey (const btc_script_op * op) static
Definition at line 175 of file script.c.
References btc_script_is_pushdata(), btc_script_op_::datalen, and btc_script_op_::op.
Referenced by btc_script_is_multisig(), and btc_script_is_pubkey().
 {
     if (!btc_script_is_pushdata(op->op))
         return false;
     if (op->datalen < 33 || op->datalen > 120)
         return false;
     return true;
 }
static btc_bool btc_script_is_op_pubkeyhash (const btc_script_op * op) static
Definition at line 184 of file script.c.
References btc_script_is_pushdata(), btc_script_op_::datalen, and btc_script_op_::op.
Referenced by btc_script_is_pubkeyhash(), and btc_script_is_scripthash().
 {
     if (!btc_script_is_pushdata(op->op))
         return false;
     if (op->datalen != 20)
         return false;
     return true;
 }
static btc_bool btc_script_is_op_smallint (const btc_script_op * op) static
Definition at line 221 of file script.c.
References btc_script_op_::op, OP_0, OP_1, and OP_16.
Referenced by btc_script_is_multisig().
 {
     return ((op->op == OP_0) ||
             (op->op >= OP_1 && op->op <= OP_16));
 }
btc_bool btc_script_is_pubkey (vector * ops)
Definition at line 194 of file script.c.
References btc_script_is_op(), btc_script_is_op_pubkey(), vector::len, OP_CHECKSIG, and vector_idx.
Referenced by btc_script_classify().
 {
     return ((ops->len == 2) &&
             btc_script_is_op(vector_idx(ops, 1), OP_CHECKSIG) &&
             btc_script_is_op_pubkey(vector_idx(ops, 0)));
 }
btc_bool btc_script_is_pubkeyhash (vector * ops)
Definition at line 202 of file script.c.
References btc_script_is_op(), btc_script_is_op_pubkeyhash(), vector::len, OP_CHECKSIG, OP_DUP, OP_EQUALVERIFY, OP_HASH160, and vector_idx.
Referenced by btc_script_classify().
 {
     return ((ops->len == 5) &&
             btc_script_is_op(vector_idx(ops, 0), OP_DUP) &&
             btc_script_is_op(vector_idx(ops, 1), OP_HASH160) &&
             btc_script_is_op_pubkeyhash(vector_idx(ops, 2)) &&
             btc_script_is_op(vector_idx(ops, 3), OP_EQUALVERIFY) &&
             btc_script_is_op(vector_idx(ops, 4), OP_CHECKSIG));
 }
static btc_bool btc_script_is_pushdata (enum opcodetype op) inline static
Definition at line 165 of file script.c.
References OP_PUSHDATA4.
Referenced by btc_script_is_op_pubkey(), and btc_script_is_op_pubkeyhash().
 {
     return (op <= OP_PUSHDATA4);
 }
btc_bool btc_script_is_scripthash (vector * ops)
Definition at line 213 of file script.c.
References btc_script_is_op(), btc_script_is_op_pubkeyhash(), vector::len, OP_EQUAL, OP_HASH160, and vector_idx.
Referenced by btc_script_classify().
 {
     return ((ops->len == 3) &&
             btc_script_is_op(vector_idx(ops, 0), OP_HASH160) &&
             btc_script_is_op_pubkeyhash(vector_idx(ops, 1)) &&
             btc_script_is_op(vector_idx(ops, 2), OP_EQUAL));
 }
void btc_script_op_free (btc_script_op * script_op)
Definition at line 90 of file script.c.
References btc_script_op_::data, btc_script_op_::datalen, btc_script_op_::op, and OP_0.
Referenced by btc_script_get_ops(), and btc_script_op_free_cb().
 {
     if (script_op->data) {
         free(script_op->data);
         script_op->data = NULL;
     }
     script_op->datalen = 0;
     script_op->op = OP_0;
 }
void btc_script_op_free_cb (void * data)
Definition at line 100 of file script.c.
References btc_script_op_free().
 {
     btc_script_op* script_op = data;
     btc_script_op_free(script_op);
     free(script_op);
 }
btc_script_op* btc_script_op_new ()
Definition at line 81 of file script.c.
Referenced by btc_script_get_ops().
 {
     btc_script_op* script_op;
     script_op = calloc(1, sizeof(*script_op));
     return script_op;
 }