libbtc: /Users/jonasschnelli/Documents/bitcoin/libbtc/include/btc/script.h File Reference
script.h File Reference
#include "btc.h"
#include "cstr.h"
#include "ecc_key.h"
#include "vector.h"
Data Structures
struct btc_script_op_
Typedefs
typedef struct btc_script_op_ btc_script_op
Enumerations
enum { SIGHASH_ALL = 1, SIGHASH_NONE = 2, SIGHASH_SINGLE = 3, SIGHASH_ANYONECANPAY = 0x80 }
enum opcodetype {
OP_0 = 0x00, OP_FALSE = OP_0, OP_PUSHDATA1 = 0x4c, OP_PUSHDATA2 = 0x4d,
OP_PUSHDATA4 = 0x4e, OP_1NEGATE = 0x4f, OP_RESERVED = 0x50, OP_1 = 0x51,
OP_TRUE = OP_1, OP_2 = 0x52, OP_3 = 0x53, OP_4 = 0x54,
OP_5 = 0x55, OP_6 = 0x56, OP_7 = 0x57, OP_8 = 0x58,
OP_9 = 0x59, OP_10 = 0x5a, OP_11 = 0x5b, OP_12 = 0x5c,
OP_13 = 0x5d, OP_14 = 0x5e, OP_15 = 0x5f, OP_16 = 0x60,
OP_NOP = 0x61, OP_VER = 0x62, OP_IF = 0x63, OP_NOTIF = 0x64,
OP_VERIF = 0x65, OP_VERNOTIF = 0x66, OP_ELSE = 0x67, OP_ENDIF = 0x68,
OP_VERIFY = 0x69, OP_RETURN = 0x6a, OP_TOALTSTACK = 0x6b, OP_FROMALTSTACK = 0x6c,
OP_2DROP = 0x6d, OP_2DUP = 0x6e, OP_3DUP = 0x6f, OP_2OVER = 0x70,
OP_2ROT = 0x71, OP_2SWAP = 0x72, OP_IFDUP = 0x73, OP_DEPTH = 0x74,
OP_DROP = 0x75, OP_DUP = 0x76, OP_NIP = 0x77, OP_OVER = 0x78,
OP_PICK = 0x79, OP_ROLL = 0x7a, OP_ROT = 0x7b, OP_SWAP = 0x7c,
OP_TUCK = 0x7d, OP_CAT = 0x7e, OP_SUBSTR = 0x7f, OP_LEFT = 0x80,
OP_RIGHT = 0x81, OP_SIZE = 0x82, OP_INVERT = 0x83, OP_AND = 0x84,
OP_OR = 0x85, OP_XOR = 0x86, OP_EQUAL = 0x87, OP_EQUALVERIFY = 0x88,
OP_RESERVED1 = 0x89, OP_RESERVED2 = 0x8a, OP_1ADD = 0x8b, OP_1SUB = 0x8c,
OP_2MUL = 0x8d, OP_2DIV = 0x8e, OP_NEGATE = 0x8f, OP_ABS = 0x90,
OP_NOT = 0x91, OP_0NOTEQUAL = 0x92, OP_ADD = 0x93, OP_SUB = 0x94,
OP_MUL = 0x95, OP_DIV = 0x96, OP_MOD = 0x97, OP_LSHIFT = 0x98,
OP_RSHIFT = 0x99, OP_BOOLAND = 0x9a, OP_BOOLOR = 0x9b, OP_NUMEQUAL = 0x9c,
OP_NUMEQUALVERIFY = 0x9d, OP_NUMNOTEQUAL = 0x9e, OP_LESSTHAN = 0x9f, OP_GREATERTHAN = 0xa0,
OP_LESSTHANOREQUAL = 0xa1, OP_GREATERTHANOREQUAL = 0xa2, OP_MIN = 0xa3, OP_MAX = 0xa4,
OP_WITHIN = 0xa5, OP_RIPEMD160 = 0xa6, OP_SHA1 = 0xa7, OP_SHA256 = 0xa8,
OP_HASH160 = 0xa9, OP_HASH256 = 0xaa, OP_CODESEPARATOR = 0xab, OP_CHECKSIG = 0xac,
OP_CHECKSIGVERIFY = 0xad, OP_CHECKMULTISIG = 0xae, OP_CHECKMULTISIGVERIFY = 0xaf, OP_NOP1 = 0xb0,
OP_NOP2 = 0xb1, OP_CHECKLOCKTIMEVERIFY = OP_NOP2, OP_NOP3 = 0xb2, OP_NOP4 = 0xb3,
OP_NOP5 = 0xb4, OP_NOP6 = 0xb5, OP_NOP7 = 0xb6, OP_NOP8 = 0xb7,
OP_NOP9 = 0xb8, OP_NOP10 = 0xb9, OP_SMALLINTEGER = 0xfa, OP_PUBKEYS = 0xfb,
OP_PUBKEYHASH = 0xfd, OP_PUBKEY = 0xfe, OP_INVALIDOPCODE = 0xff
}
enum btc_tx_out_type {
BTC_TX_NONSTANDARD, BTC_TX_PUBKEY, BTC_TX_PUBKEYHASH, BTC_TX_SCRIPTHASH,
BTC_TX_MULTISIG
}
Functions
btc_bool btc_script_copy_without_op_codeseperator (const cstring *scriptin, cstring *scriptout)
LIBBTC_API btc_script_op * btc_script_op_new ()
LIBBTC_API void btc_script_op_free (btc_script_op *script_op)
void btc_script_op_free_cb (void *data)
btc_bool btc_script_get_ops (const cstring *script_in, vector *ops_out)
enum btc_tx_out_type btc_script_classify (vector *ops)
LIBBTC_API btc_bool btc_script_build_multisig (cstring *script_in, unsigned int required_signatures, vector *pubkeys_chars)
LIBBTC_API btc_bool btc_script_build_p2pkh (cstring *script, const uint8_t *hash160)
LIBBTC_API btc_bool btc_script_build_p2sh (cstring *script_in, const uint8_t *hash160)
Typedef Documentation
typedef struct btc_script_op_ btc_script_op
Enumeration Type Documentation
anonymous enum
Signature hash types/flags
Enumerator
SIGHASH_ALL
SIGHASH_NONE
SIGHASH_SINGLE
SIGHASH_ANYONECANPAY
Definition at line 41 of file script.h.
      {
     SIGHASH_ALL = 1,
     SIGHASH_NONE = 2,
     SIGHASH_SINGLE = 3,
     SIGHASH_ANYONECANPAY = 0x80,
 };
enum btc_tx_out_type
Enumerator
BTC_TX_NONSTANDARD
BTC_TX_PUBKEY
BTC_TX_PUBKEYHASH
BTC_TX_SCRIPTHASH
BTC_TX_MULTISIG
Definition at line 193 of file script.h.
                      {
     BTC_TX_NONSTANDARD,
     // 'standard' transaction types:
     BTC_TX_PUBKEY,
     BTC_TX_PUBKEYHASH,
     BTC_TX_SCRIPTHASH,
     BTC_TX_MULTISIG,
 };
enum opcodetype
Script opcodes
Enumerator
OP_0
OP_FALSE
OP_PUSHDATA1
OP_PUSHDATA2
OP_PUSHDATA4
OP_1NEGATE
OP_RESERVED
OP_1
OP_TRUE
OP_2
OP_3
OP_4
OP_5
OP_6
OP_7
OP_8
OP_9
OP_10
OP_11
OP_12
OP_13
OP_14
OP_15
OP_16
OP_NOP
OP_VER
OP_IF
OP_NOTIF
OP_VERIF
OP_VERNOTIF
OP_ELSE
OP_ENDIF
OP_VERIFY
OP_RETURN
OP_TOALTSTACK
OP_FROMALTSTACK
OP_2DROP
OP_2DUP
OP_3DUP
OP_2OVER
OP_2ROT
OP_2SWAP
OP_IFDUP
OP_DEPTH
OP_DROP
OP_DUP
OP_NIP
OP_OVER
OP_PICK
OP_ROLL
OP_ROT
OP_SWAP
OP_TUCK
OP_CAT
OP_SUBSTR
OP_LEFT
OP_RIGHT
OP_SIZE
OP_INVERT
OP_AND
OP_OR
OP_XOR
OP_EQUAL
OP_EQUALVERIFY
OP_RESERVED1
OP_RESERVED2
OP_1ADD
OP_1SUB
OP_2MUL
OP_2DIV
OP_NEGATE
OP_ABS
OP_NOT
OP_0NOTEQUAL
OP_ADD
OP_SUB
OP_MUL
OP_DIV
OP_MOD
OP_LSHIFT
OP_RSHIFT
OP_BOOLAND
OP_BOOLOR
OP_NUMEQUAL
OP_NUMEQUALVERIFY
OP_NUMNOTEQUAL
OP_LESSTHAN
OP_GREATERTHAN
OP_LESSTHANOREQUAL
OP_GREATERTHANOREQUAL
OP_MIN
OP_MAX
OP_WITHIN
OP_RIPEMD160
OP_SHA1
OP_SHA256
OP_HASH160
OP_HASH256
OP_CODESEPARATOR
OP_CHECKSIG
OP_CHECKSIGVERIFY
OP_CHECKMULTISIG
OP_CHECKMULTISIGVERIFY
OP_NOP1
OP_NOP2
OP_CHECKLOCKTIMEVERIFY
OP_NOP3
OP_NOP4
OP_NOP5
OP_NOP6
OP_NOP7
OP_NOP8
OP_NOP9
OP_NOP10
OP_SMALLINTEGER
OP_PUBKEYS
OP_PUBKEYHASH
OP_PUBKEY
OP_INVALIDOPCODE
Definition at line 49 of file script.h.
                 {
     // push value
     OP_0 = 0x00,
     OP_FALSE = OP_0,
     OP_PUSHDATA1 = 0x4c,
     OP_PUSHDATA2 = 0x4d,
     OP_PUSHDATA4 = 0x4e,
     OP_1NEGATE = 0x4f,
     OP_RESERVED = 0x50,
     OP_1 = 0x51,
     OP_TRUE = OP_1,
     OP_2 = 0x52,
     OP_3 = 0x53,
     OP_4 = 0x54,
     OP_5 = 0x55,
     OP_6 = 0x56,
     OP_7 = 0x57,
     OP_8 = 0x58,
     OP_9 = 0x59,
     OP_10 = 0x5a,
     OP_11 = 0x5b,
     OP_12 = 0x5c,
     OP_13 = 0x5d,
     OP_14 = 0x5e,
     OP_15 = 0x5f,
     OP_16 = 0x60,
     // control
     OP_NOP = 0x61,
     OP_VER = 0x62,
     OP_IF = 0x63,
     OP_NOTIF = 0x64,
     OP_VERIF = 0x65,
     OP_VERNOTIF = 0x66,
     OP_ELSE = 0x67,
     OP_ENDIF = 0x68,
     OP_VERIFY = 0x69,
     OP_RETURN = 0x6a,
     // stack ops
     OP_TOALTSTACK = 0x6b,
     OP_FROMALTSTACK = 0x6c,
     OP_2DROP = 0x6d,
     OP_2DUP = 0x6e,
     OP_3DUP = 0x6f,
     OP_2OVER = 0x70,
     OP_2ROT = 0x71,
     OP_2SWAP = 0x72,
     OP_IFDUP = 0x73,
     OP_DEPTH = 0x74,
     OP_DROP = 0x75,
     OP_DUP = 0x76,
     OP_NIP = 0x77,
     OP_OVER = 0x78,
     OP_PICK = 0x79,
     OP_ROLL = 0x7a,
     OP_ROT = 0x7b,
     OP_SWAP = 0x7c,
     OP_TUCK = 0x7d,
     // splice ops
     OP_CAT = 0x7e,
     OP_SUBSTR = 0x7f,
     OP_LEFT = 0x80,
     OP_RIGHT = 0x81,
     OP_SIZE = 0x82,
     // bit logic
     OP_INVERT = 0x83,
     OP_AND = 0x84,
     OP_OR = 0x85,
     OP_XOR = 0x86,
     OP_EQUAL = 0x87,
     OP_EQUALVERIFY = 0x88,
     OP_RESERVED1 = 0x89,
     OP_RESERVED2 = 0x8a,
     // numeric
     OP_1ADD = 0x8b,
     OP_1SUB = 0x8c,
     OP_2MUL = 0x8d,
     OP_2DIV = 0x8e,
     OP_NEGATE = 0x8f,
     OP_ABS = 0x90,
     OP_NOT = 0x91,
     OP_0NOTEQUAL = 0x92,
     OP_ADD = 0x93,
     OP_SUB = 0x94,
     OP_MUL = 0x95,
     OP_DIV = 0x96,
     OP_MOD = 0x97,
     OP_LSHIFT = 0x98,
     OP_RSHIFT = 0x99,
     OP_BOOLAND = 0x9a,
     OP_BOOLOR = 0x9b,
     OP_NUMEQUAL = 0x9c,
     OP_NUMEQUALVERIFY = 0x9d,
     OP_NUMNOTEQUAL = 0x9e,
     OP_LESSTHAN = 0x9f,
     OP_GREATERTHAN = 0xa0,
     OP_LESSTHANOREQUAL = 0xa1,
     OP_GREATERTHANOREQUAL = 0xa2,
     OP_MIN = 0xa3,
     OP_MAX = 0xa4,
     OP_WITHIN = 0xa5,
     // crypto
     OP_RIPEMD160 = 0xa6,
     OP_SHA1 = 0xa7,
     OP_SHA256 = 0xa8,
     OP_HASH160 = 0xa9,
     OP_HASH256 = 0xaa,
     OP_CODESEPARATOR = 0xab,
     OP_CHECKSIG = 0xac,
     OP_CHECKSIGVERIFY = 0xad,
     OP_CHECKMULTISIG = 0xae,
     OP_CHECKMULTISIGVERIFY = 0xaf,
     // expansion
     OP_NOP1 = 0xb0,
     OP_NOP2 = 0xb1,
     OP_CHECKLOCKTIMEVERIFY = OP_NOP2,
     OP_NOP3 = 0xb2,
     OP_NOP4 = 0xb3,
     OP_NOP5 = 0xb4,
     OP_NOP6 = 0xb5,
     OP_NOP7 = 0xb6,
     OP_NOP8 = 0xb7,
     OP_NOP9 = 0xb8,
     OP_NOP10 = 0xb9,
     // template matching params
     OP_SMALLINTEGER = 0xfa,
     OP_PUBKEYS = 0xfb,
     OP_PUBKEYHASH = 0xfd,
     OP_PUBKEY = 0xfe,
     OP_INVALIDOPCODE = 0xff,
 };
Function Documentation
LIBBTC_API btc_bool btc_script_build_multisig (cstring * script_in, unsigned int required_signatures, vector * pubkeys_chars)
Definition at line 298 of file script.c.
References BTC_ECKEY_COMPRESSED_LENGTH, BTC_ECKEY_UNCOMPRESSED_LENGTH, btc_encode_op_n(), btc_script_append_pushdata(), btc_pubkey_::compressed, cstr_append_buf(), cstr_resize(), vector::data, vector::len, OP_CHECKMULTISIG, and btc_pubkey_::pubkey.
 {
     cstr_resize(script_in, 0); //clear script
     if(required_signatures > 16 || pubkeys_chars->len > 16)
         return false;
     enum opcodetype op_req_sig = btc_encode_op_n(required_signatures);
     cstr_append_buf(script_in, &op_req_sig, 1);
     int i;
     for (i = 0; i < (int)pubkeys_chars->len; i++)
     {
         btc_pubkey *pkey = pubkeys_chars->data[i];
         btc_script_append_pushdata(script_in, pkey->pubkey, (pkey->compressed ? BTC_ECKEY_COMPRESSED_LENGTH : BTC_ECKEY_UNCOMPRESSED_LENGTH));
     }
     enum opcodetype op_pub_len = btc_encode_op_n(pubkeys_chars->len);
     cstr_append_buf(script_in, &op_pub_len, 1);
     enum opcodetype op_checkmultisig = OP_CHECKMULTISIG;
     cstr_append_buf(script_in, &op_checkmultisig, 1);
     return true;
 }
LIBBTC_API btc_bool btc_script_build_p2pkh (cstring * script, const uint8_t * hash160)
Definition at line 323 of file script.c.
References btc_script_append_op(), btc_script_append_pushdata(), cstr_resize(), OP_CHECKSIG, OP_DUP, OP_EQUALVERIFY, and OP_HASH160.
Referenced by btc_tx_add_p2pkh_hash160_out().
 {
     cstr_resize(script_in, 0); //clear script
     btc_script_append_op(script_in, OP_DUP);
     btc_script_append_op(script_in, OP_HASH160);
     btc_script_append_pushdata(script_in, hash160, 20);
     btc_script_append_op(script_in, OP_EQUALVERIFY);
     btc_script_append_op(script_in, OP_CHECKSIG);
     return true;
 }
LIBBTC_API btc_bool btc_script_build_p2sh (cstring * script_in, const uint8_t * hash160)
Definition at line 338 of file script.c.
References btc_script_append_op(), btc_script_append_pushdata(), cstr_resize(), OP_EQUAL, and OP_HASH160.
Referenced by btc_tx_add_p2sh_hash160_out().
 {
     cstr_resize(script_in, 0); //clear script
     btc_script_append_op(script_in, OP_HASH160);
     btc_script_append_pushdata(script_in, hash160, 20);
     btc_script_append_op(script_in, OP_EQUAL);
     return true;
 }
enum btc_tx_out_type btc_script_classify (vector * ops)
Definition at line 243 of file script.c.
References btc_script_is_multisig(), btc_script_is_pubkey(), btc_script_is_pubkeyhash(), btc_script_is_scripthash(), BTC_TX_MULTISIG, BTC_TX_NONSTANDARD, BTC_TX_PUBKEY, BTC_TX_PUBKEYHASH, and BTC_TX_SCRIPTHASH.
 {
     if (btc_script_is_pubkeyhash(ops))
         return BTC_TX_PUBKEYHASH;
     if (btc_script_is_scripthash(ops))
         return BTC_TX_SCRIPTHASH;
     if (btc_script_is_pubkey(ops))
         return BTC_TX_PUBKEY;
     if (btc_script_is_multisig(ops))
         return BTC_TX_MULTISIG;
     return BTC_TX_NONSTANDARD;
 }
btc_bool btc_script_copy_without_op_codeseperator (const cstring * scriptin, cstring * scriptout)
Definition at line 36 of file script.c.
References cstr_append_buf(), deser_bytes(), deser_skip(), deser_u16(), deser_u32(), const_buffer::len, cstring::len, OP_CODESEPARATOR, OP_PUSHDATA1, OP_PUSHDATA2, OP_PUSHDATA4, const_buffer::p, and cstring::str.
Referenced by btc_tx_sighash().
 {
     if (script_in->len == 0)
         return false; /* EOF */
     struct const_buffer buf = {script_in->str, script_in->len};
     unsigned char opcode;
     while (buf.len > 0) {
         if (!deser_bytes(&opcode, &buf, 1))
             goto err_out;
         uint32_t data_len;
         if (opcode == OP_CODESEPARATOR)
             continue;
         else if (opcode == OP_PUSHDATA1) {
             uint8_t v8;
             if (!deser_bytes(&v8, &buf, 1))
                 goto err_out;
             data_len = v8;
         } else if (opcode == OP_PUSHDATA2) {
             uint16_t v16;
             if (!deser_u16(&v16, &buf))
                 goto err_out;
             data_len = v16;
         } else if (opcode == OP_PUSHDATA4) {
             uint32_t v32;
             if (!deser_u32(&v32, &buf))
                 goto err_out;
             data_len = v32;
         } else {
             cstr_append_buf(script_out, &opcode, 1);
             continue;
         }
         cstr_append_buf(script_out, buf.p, data_len);
         if (!deser_skip(&buf, data_len))
             goto err_out;
     }
 err_out:
     return false;
 }
btc_bool btc_script_get_ops (const cstring * script_in, vector * ops_out)
Definition at line 108 of file script.c.
References btc_script_op_free(), btc_script_op_new(), btc_script_op_::data, btc_script_op_::datalen, deser_bytes(), deser_skip(), deser_u16(), deser_u32(), const_buffer::len, cstring::len, btc_script_op_::op, OP_PUSHDATA1, OP_PUSHDATA2, OP_PUSHDATA4, const_buffer::p, cstring::str, and vector_add().
 {
     if (script_in->len == 0)
         return false; /* EOF */
     struct const_buffer buf = {script_in->str, script_in->len};
     unsigned char opcode;
     btc_script_op* op = NULL;
     while (buf.len > 0) {
         op = btc_script_op_new();
         if (!deser_bytes(&opcode, &buf, 1))
             goto err_out;
         op->op = opcode;
         uint32_t data_len;
         if (opcode < OP_PUSHDATA1) {
             data_len = opcode;
         } else if (opcode == OP_PUSHDATA1) {
             uint8_t v8;
             if (!deser_bytes(&v8, &buf, 1))
                 goto err_out;
             data_len = v8;
         } else if (opcode == OP_PUSHDATA2) {
             uint16_t v16;
             if (!deser_u16(&v16, &buf))
                 goto err_out;
             data_len = v16;
         } else if (opcode == OP_PUSHDATA4) {
             uint32_t v32;
             if (!deser_u32(&v32, &buf))
                 goto err_out;
             data_len = v32;
         } else {
             vector_add(ops_out, op);
             continue;
         }
         op->data = calloc(1, data_len);
         memcpy(op->data, &buf.p, data_len);
         op->datalen = data_len;
         vector_add(ops_out, op);
         if (!deser_skip(&buf, data_len))
             goto err_out;
     }
     return true;
 err_out:
     btc_script_op_free(op);
     return false;
 }
LIBBTC_API void btc_script_op_free (btc_script_op * script_op)
Definition at line 90 of file script.c.
References btc_script_op_::data, btc_script_op_::datalen, btc_script_op_::op, and OP_0.
Referenced by btc_script_get_ops(), and btc_script_op_free_cb().
 {
     if (script_op->data) {
         free(script_op->data);
         script_op->data = NULL;
     }
     script_op->datalen = 0;
     script_op->op = OP_0;
 }
void btc_script_op_free_cb (void * data)
Definition at line 100 of file script.c.
References btc_script_op_free().
 {
     btc_script_op* script_op = data;
     btc_script_op_free(script_op);
     free(script_op);
 }
LIBBTC_API btc_script_op* btc_script_op_new ()
Definition at line 81 of file script.c.
Referenced by btc_script_get_ops().
 {
     btc_script_op* script_op;
     script_op = calloc(1, sizeof(*script_op));
     return script_op;
 }