libbtc: /Users/jonasschnelli/Documents/bitcoin/libbtc/src/serialize.h File Reference
serialize.h File Reference
#include <stdint.h>
#include "buffer.h"
#include "btc/cstr.h"
#include "btc/vector.h"
#include "portable_endian.h"
Functions
void ser_bytes (cstring *s, const void *p, size_t len)
void ser_u16 (cstring *s, uint16_t v_)
void ser_u32 (cstring *s, uint32_t v_)
void ser_u64 (cstring *s, uint64_t v_)
static void ser_u256 (cstring *s, const unsigned char *v_)
void ser_varlen (cstring *s, uint32_t vlen)
void ser_str (cstring *s, const char *s_in, size_t maxlen)
void ser_varstr (cstring *s, cstring *s_in)
static void ser_s32 (cstring *s, int32_t v_)
static void ser_s64 (cstring *s, int64_t v_)
void ser_u256_vector (cstring *s, vector *vec)
btc_bool deser_skip (struct const_buffer *buf, size_t len)
btc_bool deser_bytes (void *po, struct const_buffer *buf, size_t len)
btc_bool deser_u16 (uint16_t *vo, struct const_buffer *buf)
btc_bool deser_u32 (uint32_t *vo, struct const_buffer *buf)
btc_bool deser_u64 (uint64_t *vo, struct const_buffer *buf)
static btc_bool deser_u256 (uint8_t *vo, struct const_buffer *buf)
btc_bool deser_varlen (uint32_t *lo, struct const_buffer *buf)
btc_bool deser_str (char *so, struct const_buffer *buf, size_t maxlen)
btc_bool deser_varstr (cstring **so, struct const_buffer *buf)
static btc_bool deser_s64 (int64_t *vo, struct const_buffer *buf)
btc_bool deser_u256_vector (vector **vo, struct const_buffer *buf)
Function Documentation
btc_bool deser_bytes (void * po, struct const_buffer * buf, size_t len)
Definition at line 103 of file serialize.c.
References const_buffer::len, and const_buffer::p.
Referenced by btc_script_copy_without_op_codeseperator(), btc_script_get_ops(), deser_str(), deser_u16(), deser_u256(), deser_u32(), deser_u64(), and deser_varlen().
 {
     if (buf->len < len)
         return false;
     memcpy(po, buf->p, len);
     buf->p += len;
     buf->len -= len;
     return true;
 }
static btc_bool deser_s64 (int64_t * vo, struct const_buffer * buf) inline static
Definition at line 80 of file serialize.h.
References deser_u64().
Referenced by btc_tx_out_deserialize().
 {
     return deser_u64((uint64_t*)vo, buf);
 }
btc_bool deser_skip (struct const_buffer * buf, size_t len)
Definition at line 92 of file serialize.c.
References const_buffer::len, and const_buffer::p.
Referenced by btc_script_copy_without_op_codeseperator(), btc_script_get_ops(), and deser_str().
 {
     if (buf->len < len)
         return false;
     buf->p += len;
     buf->len -= len;
     return true;
 }
btc_bool deser_str (char * so, struct const_buffer * buf, size_t maxlen)
Definition at line 178 of file serialize.c.
References deser_bytes(), deser_skip(), deser_varlen(), and const_buffer::len.
 {
     uint32_t len;
     if (!deser_varlen(&len, buf))
         return false;
     /* if input larger than buffer, truncate copy, skip remainder */
     uint32_t skip_len = 0;
     if (len > maxlen) {
         skip_len = len - maxlen;
         len = maxlen;
     }
     if (!deser_bytes(so, buf, len))
         return false;
     if (!deser_skip(buf, skip_len))
         return false;
     /* add C string null */
     if (len < maxlen)
         so[len] = 0;
     else
         so[maxlen - 1] = 0;
     return true;
 }
btc_bool deser_u16 (uint16_t * vo, struct const_buffer * buf)
Definition at line 115 of file serialize.c.
References deser_bytes().
Referenced by btc_script_copy_without_op_codeseperator(), btc_script_get_ops(), and deser_varlen().
 {
     uint16_t v;
     if (!deser_bytes(&v, buf, sizeof(v)))
         return false;
     *vo = le16toh(v);
     return true;
 }
static btc_bool deser_u256 (uint8_t * vo, struct const_buffer * buf) inline static
Definition at line 71 of file serialize.h.
References deser_bytes().
Referenced by btc_tx_in_deserialize(), and deser_u256_vector().
 {
     return deser_bytes(vo, buf, 32);
 }
btc_bool deser_u256_vector (vector ** vo, struct const_buffer * buf)
Definition at line 230 of file serialize.c.
References deser_u256(), deser_varlen(), vector_add(), vector_free(), and vector_new().
 {
     vector* vec = *vo;
     if (vec) {
         vector_free(vec, true);
         *vo = vec = NULL;
     }
     uint32_t vlen;
     if (!deser_varlen(&vlen, buf))
         return false;
     if (!vlen)
         return true;
     vec = vector_new(vlen, free);
     if (!vec)
         return false;
     unsigned int i;
     for (i = 0; i < vlen; i++) {
         uint8_t* n = malloc(32);
         if (!deser_u256(n, buf)) {
             free(n);
             goto err_out;
         }
         vector_add(vec, n);
     }
     *vo = vec;
     return true;
 err_out:
     vector_free(vec, true);
     return false;
 }
btc_bool deser_u32 (uint32_t * vo, struct const_buffer * buf)
Definition at line 126 of file serialize.c.
References deser_bytes().
Referenced by btc_script_copy_without_op_codeseperator(), btc_script_get_ops(), btc_tx_deserialize(), btc_tx_in_deserialize(), and deser_varlen().
 {
     uint32_t v;
     if (!deser_bytes(&v, buf, sizeof(v)))
         return false;
     *vo = le32toh(v);
     return true;
 }
btc_bool deser_u64 (uint64_t * vo, struct const_buffer * buf)
Definition at line 137 of file serialize.c.
References deser_bytes().
Referenced by deser_s64(), and deser_varlen().
 {
     uint64_t v;
     if (!deser_bytes(&v, buf, sizeof(v)))
         return false;
     *vo = le64toh(v);
     return true;
 }
btc_bool deser_varlen (uint32_t * lo, struct const_buffer * buf)
Definition at line 148 of file serialize.c.
References deser_bytes(), deser_u16(), deser_u32(), deser_u64(), and const_buffer::len.
Referenced by btc_tx_deserialize(), deser_str(), deser_u256_vector(), and deser_varstr().
 {
     uint32_t len;
     unsigned char c;
     if (!deser_bytes(&c, buf, 1))
         return false;
     if (c == 253) {
         uint16_t v16;
         if (!deser_u16(&v16, buf))
             return false;
         len = v16;
     } else if (c == 254) {
         uint32_t v32;
         if (!deser_u32(&v32, buf))
             return false;
         len = v32;
     } else if (c == 255) {
         uint64_t v64;
         if (!deser_u64(&v64, buf))
             return false;
         len = (uint32_t)v64; /* WARNING: truncate */
     } else
         len = c;
     *lo = len;
     return true;
 }
btc_bool deser_varstr (cstring ** so, struct const_buffer * buf)
Definition at line 205 of file serialize.c.
References cstr_append_buf(), cstr_free(), cstr_new_sz(), deser_varlen(), const_buffer::len, and const_buffer::p.
Referenced by btc_tx_in_deserialize(), and btc_tx_out_deserialize().
 {
     if (*so) {
         cstr_free(*so, true);
         *so = NULL;
     }
     uint32_t len;
     if (!deser_varlen(&len, buf))
         return false;
     if (buf->len < len)
         return false;
     cstring* s = cstr_new_sz(len);
     cstr_append_buf(s, buf->p, len);
     buf->p += len;
     buf->len -= len;
     *so = s;
     return true;
 }
void ser_bytes (cstring * s, const void * p, size_t len)
Definition at line 13 of file serialize.c.
References cstr_append_buf().
Referenced by ser_str(), ser_u256(), ser_varlen(), and ser_varstr().
 {
     cstr_append_buf(s, p, len);
 }
static void ser_s32 (cstring * s, int32_t v_) inline static
Definition at line 53 of file serialize.h.
References ser_u32().
Referenced by btc_tx_sighash().
 {
     ser_u32(s, (uint32_t)v_);
 }
static void ser_s64 (cstring * s, int64_t v_) inline static
Definition at line 58 of file serialize.h.
References ser_u64().
Referenced by btc_tx_out_serialize().
 {
     ser_u64(s, (uint64_t)v_);
 }
void ser_str (cstring * s, const char * s_in, size_t maxlen)
Definition at line 60 of file serialize.c.
References ser_bytes(), and ser_varlen().
 {
     size_t slen = strnlen(s_in, maxlen);
     ser_varlen(s, slen);
     ser_bytes(s, s_in, slen);
 }
void ser_u16 (cstring * s, uint16_t v_)
Definition at line 18 of file serialize.c.
References cstr_append_buf().
Referenced by ser_varlen().
 {
     uint16_t v = htole16(v_);
     cstr_append_buf(s, &v, sizeof(v));
 }
static void ser_u256 (cstring * s, const unsigned char * v_) inline static
Definition at line 44 of file serialize.h.
References ser_bytes().
Referenced by btc_tx_in_serialize(), and ser_u256_vector().
 {
     ser_bytes(s, v_, 32);
 }
void ser_u256_vector (cstring * s, vector * vec)
Definition at line 79 of file serialize.c.
References vector::len, ser_u256(), ser_varlen(), and vector_idx.
 {
     unsigned int vec_len = vec ? vec->len : 0;
     ser_varlen(s, vec_len);
     unsigned int i;
     for (i = 0; i < vec_len; i++) {
         uint8_t* av = vector_idx(vec, i);
         ser_u256(s, av);
     }
 }
void ser_u32 (cstring * s, uint32_t v_)
Definition at line 24 of file serialize.c.
References cstr_append_buf().
Referenced by btc_tx_in_serialize(), btc_tx_serialize(), ser_s32(), and ser_varlen().
 {
     uint32_t v = htole32(v_);
     cstr_append_buf(s, &v, sizeof(v));
 }
void ser_u64 (cstring * s, uint64_t v_)
Definition at line 30 of file serialize.c.
References cstr_append_buf().
Referenced by ser_s64().
 {
     uint64_t v = htole64(v_);
     cstr_append_buf(s, &v, sizeof(v));
 }
void ser_varlen (cstring * s, uint32_t vlen)
Definition at line 36 of file serialize.c.
References ser_bytes(), ser_u16(), and ser_u32().
Referenced by btc_tx_serialize(), ser_str(), ser_u256_vector(), and ser_varstr().
 {
     unsigned char c;
     if (vlen < 253) {
         c = vlen;
         ser_bytes(s, &c, 1);
     }
     else if (vlen < 0x10000) {
         c = 253;
         ser_bytes(s, &c, 1);
         ser_u16(s, (uint16_t)vlen);
     }
     else {
         c = 254;
         ser_bytes(s, &c, 1);
         ser_u32(s, vlen);
     }
     /* u64 case intentionally not implemented */
 }
void ser_varstr (cstring * s, cstring * s_in)
Definition at line 68 of file serialize.c.
References cstring::len, ser_bytes(), ser_varlen(), and cstring::str.
Referenced by btc_tx_in_serialize(), and btc_tx_out_serialize().
 {
     if (!s_in || !s_in->len) {
         ser_varlen(s, 0);
         return;
     }
     ser_varlen(s, s_in->len);
     ser_bytes(s, s_in->str, s_in->len);
 }