libbtc: /Users/jonasschnelli/Documents/bitcoin/libbtc/src/vector.c File Reference
vector.c File Reference
#include "btc/vector.h"
#include <string.h>
Functions
vector * vector_new (size_t res, void(*free_f)(void *))
static void vector_free_data (vector *vec)
void vector_free (vector *vec, btc_bool free_array)
static btc_bool vector_grow (vector *vec, size_t min_sz)
ssize_t vector_find (vector *vec, void *data)
btc_bool vector_add (vector *vec, void *data)
void vector_remove_range (vector *vec, size_t pos, size_t len)
void vector_remove_idx (vector *vec, size_t pos)
btc_bool vector_remove (vector *vec, void *data)
btc_bool vector_resize (vector *vec, size_t newsz)
Function Documentation
btc_bool vector_add (vector * vec, void * data)
Definition at line 113 of file vector.c.
References vector::alloc, vector::data, vector::len, and vector_grow().
Referenced by btc_script_get_ops(), btc_tx_add_p2pkh_hash160_out(), btc_tx_add_p2sh_hash160_out(), btc_tx_copy(), btc_tx_deserialize(), and deser_u256_vector().
 {
     if (vec->len == vec->alloc)
         if (!vector_grow(vec, vec->len + 1))
             return false;
     vec->data[vec->len] = data;
     vec->len++;
     return true;
 }
ssize_t vector_find (vector * vec, void * data)
Definition at line 101 of file vector.c.
References vector::data, and vector::len.
Referenced by vector_remove().
 {
     if (vec && vec->len) {
         size_t i;
         for (i = 0; i < vec->len; i++)
             if (vec->data[i] == data)
                 return (ssize_t)i;
     }
     return -1;
 }
void vector_free (vector * vec, btc_bool free_array)
Definition at line 71 of file vector.c.
References vector_free_data().
Referenced by btc_tx_copy(), btc_tx_free(), btc_tx_sighash(), and deser_u256_vector().
 {
     if (!vec)
         return;
     if (free_array)
         vector_free_data(vec);
     memset(vec, 0, sizeof(*vec));
     free(vec);
 }
static void vector_free_data (vector * vec) static
Definition at line 51 of file vector.c.
References vector::alloc, vector::data, vector::elem_free_f, and vector::len.
Referenced by vector_free().
 {
     if (!vec->data)
         return;
     if (vec->elem_free_f) {
         unsigned int i;
         for (i = 0; i < vec->len; i++)
             if (vec->data[i]) {
                 vec->elem_free_f(vec->data[i]);
                 vec->data[i] = NULL;
             }
     }
     free(vec->data);
     vec->data = NULL;
     vec->alloc = 0;
     vec->len = 0;
 }
static btc_bool vector_grow (vector * vec, size_t min_sz) static
Definition at line 83 of file vector.c.
References vector::alloc, and vector::data.
Referenced by vector_add(), and vector_resize().
 {
     size_t new_alloc = vec->alloc;
     while (new_alloc < min_sz)
         new_alloc *= 2;
     if (vec->alloc == new_alloc)
         return true;
     void* new_data = realloc(vec->data, new_alloc * sizeof(void*));
     if (!new_data)
         return false;
     vec->data = new_data;
     vec->alloc = new_alloc;
     return true;
 }
vector* vector_new (size_t res, void(*)(void *) free_f)
Definition at line 31 of file vector.c.
References vector::alloc, vector::data, and vector::elem_free_f.
Referenced by btc_tx_copy(), btc_tx_new(), btc_tx_sighash(), and deser_u256_vector().
 {
     vector* vec = calloc(1, sizeof(vector));
     if (!vec)
         return NULL;
     vec->alloc = 8;
     while (vec->alloc < res)
         vec->alloc *= 2;
     vec->elem_free_f = free_f;
     vec->data = malloc(vec->alloc * sizeof(void*));
     if (!vec->data) {
         free(vec);
         return NULL;
     }
     return vec;
 }
btc_bool vector_remove (vector * vec, void * data)
Definition at line 144 of file vector.c.
References vector_find(), and vector_remove_idx().
 {
     ssize_t idx = vector_find(vec, data);
     if (idx < 0)
         return false;
     vector_remove_idx(vec, idx);
     return true;
 }
void vector_remove_idx (vector * vec, size_t pos)
Definition at line 139 of file vector.c.
References vector_remove_range().
Referenced by vector_remove().
 {
     vector_remove_range(vec, pos, 1);
 }
void vector_remove_range (vector * vec, size_t pos, size_t len)
Definition at line 124 of file vector.c.
References vector::data, vector::elem_free_f, const_buffer::len, and vector::len.
Referenced by btc_tx_sighash(), and vector_remove_idx().
 {
     if (!vec || ((pos + len) > vec->len))
         return;
     if (vec->elem_free_f) {
         unsigned int i, count;
         for (i = pos, count = 0; count < len; i++, count++)
             vec->elem_free_f(vec->data[i]);
     }
     memmove(&vec->data[pos], &vec->data[pos + len], (vec->len - pos - len) * sizeof(void*));
     vec->len -= len;
 }
btc_bool vector_resize (vector * vec, size_t newsz)
Definition at line 154 of file vector.c.
References vector::data, vector::elem_free_f, const_buffer::len, vector::len, and vector_grow().
Referenced by btc_tx_sighash().
 {
     unsigned int i;
     /* same size */
     if (newsz == vec->len)
         return true;
     /* truncate */
     else if (newsz < vec->len) {
         size_t del_count = vec->len - newsz;
         for (i = (vec->len - del_count); i < vec->len; i++) {
             if (vec->elem_free_f)
                 vec->elem_free_f(vec->data[i]);
             vec->data[i] = NULL;
         }
         vec->len = newsz;
         return true;
     }
     /* last possibility: grow */
     if (!vector_grow(vec, newsz))
         return false;
     /* set new elements to NULL */
     for (i = vec->len; i < newsz; i++)
         vec->data[i] = NULL;
     return true;
 }