libbtc: /Users/jonasschnelli/Documents/bitcoin/libbtc/include/btc/vector.h File Reference
vector.h File Reference
#include "btc.h"
#include <stdlib.h>
#include <sys/types.h>
Data Structures
struct vector
Macros
#define vector_idx(vec, idx) ((vec)->data[(idx)])
Typedefs
typedef struct vector vector
Functions
LIBBTC_API vector * vector_new (size_t res, void(*free_f)(void *))
LIBBTC_API void vector_free (vector *vec, btc_bool free_array)
LIBBTC_API btc_bool vector_add (vector *vec, void *data)
LIBBTC_API btc_bool vector_remove (vector *vec, void *data)
LIBBTC_API void vector_remove_idx (vector *vec, size_t idx)
LIBBTC_API void vector_remove_range (vector *vec, size_t idx, size_t len)
LIBBTC_API btc_bool vector_resize (vector *vec, size_t newsz)
LIBBTC_API ssize_t vector_find (vector *vec, void *data)
Macro Definition Documentation
#define vector_idx (vec, idx) ((vec)->data[(idx)])
Definition at line 59 of file vector.h.
Referenced by btc_script_is_multisig(), btc_script_is_pubkey(), btc_script_is_pubkeyhash(), btc_script_is_scripthash(), btc_tx_copy(), btc_tx_serialize(), btc_tx_sighash(), and ser_u256_vector().
Typedef Documentation
typedef struct vector vector
Function Documentation
LIBBTC_API btc_bool vector_add (vector * vec, void * data)
Definition at line 113 of file vector.c.
References vector::alloc, vector::data, vector::len, and vector_grow().
Referenced by btc_script_get_ops(), btc_tx_add_p2pkh_hash160_out(), btc_tx_add_p2sh_hash160_out(), btc_tx_copy(), btc_tx_deserialize(), and deser_u256_vector().
 {
     if (vec->len == vec->alloc)
         if (!vector_grow(vec, vec->len + 1))
             return false;
     vec->data[vec->len] = data;
     vec->len++;
     return true;
 }
LIBBTC_API ssize_t vector_find (vector * vec, void * data)
Definition at line 101 of file vector.c.
References vector::data, and vector::len.
Referenced by vector_remove().
 {
     if (vec && vec->len) {
         size_t i;
         for (i = 0; i < vec->len; i++)
             if (vec->data[i] == data)
                 return (ssize_t)i;
     }
     return -1;
 }
LIBBTC_API void vector_free (vector * vec, btc_bool free_array)
Definition at line 71 of file vector.c.
References vector_free_data().
Referenced by btc_tx_copy(), btc_tx_free(), btc_tx_sighash(), and deser_u256_vector().
 {
     if (!vec)
         return;
     if (free_array)
         vector_free_data(vec);
     memset(vec, 0, sizeof(*vec));
     free(vec);
 }
LIBBTC_API vector* vector_new (size_t res, void(*)(void *) free_f)
Definition at line 31 of file vector.c.
References vector::alloc, vector::data, and vector::elem_free_f.
Referenced by btc_tx_copy(), btc_tx_new(), btc_tx_sighash(), and deser_u256_vector().
 {
     vector* vec = calloc(1, sizeof(vector));
     if (!vec)
         return NULL;
     vec->alloc = 8;
     while (vec->alloc < res)
         vec->alloc *= 2;
     vec->elem_free_f = free_f;
     vec->data = malloc(vec->alloc * sizeof(void*));
     if (!vec->data) {
         free(vec);
         return NULL;
     }
     return vec;
 }
LIBBTC_API btc_bool vector_remove (vector * vec, void * data)
Definition at line 144 of file vector.c.
References vector_find(), and vector_remove_idx().
 {
     ssize_t idx = vector_find(vec, data);
     if (idx < 0)
         return false;
     vector_remove_idx(vec, idx);
     return true;
 }
LIBBTC_API void vector_remove_idx (vector * vec, size_t idx)
Definition at line 139 of file vector.c.
References vector_remove_range().
Referenced by vector_remove().
 {
     vector_remove_range(vec, pos, 1);
 }
LIBBTC_API void vector_remove_range (vector * vec, size_t idx, size_t len)
Definition at line 124 of file vector.c.
References vector::data, vector::elem_free_f, const_buffer::len, and vector::len.
Referenced by btc_tx_sighash(), and vector_remove_idx().
 {
     if (!vec || ((pos + len) > vec->len))
         return;
     if (vec->elem_free_f) {
         unsigned int i, count;
         for (i = pos, count = 0; count < len; i++, count++)
             vec->elem_free_f(vec->data[i]);
     }
     memmove(&vec->data[pos], &vec->data[pos + len], (vec->len - pos - len) * sizeof(void*));
     vec->len -= len;
 }
LIBBTC_API btc_bool vector_resize (vector * vec, size_t newsz)
Definition at line 154 of file vector.c.
References vector::data, vector::elem_free_f, const_buffer::len, vector::len, and vector_grow().
Referenced by btc_tx_sighash().
 {
     unsigned int i;
     /* same size */
     if (newsz == vec->len)
         return true;
     /* truncate */
     else if (newsz < vec->len) {
         size_t del_count = vec->len - newsz;
         for (i = (vec->len - del_count); i < vec->len; i++) {
             if (vec->elem_free_f)
                 vec->elem_free_f(vec->data[i]);
             vec->data[i] = NULL;
         }
         vec->len = newsz;
         return true;
     }
     /* last possibility: grow */
     if (!vector_grow(vec, newsz))
         return false;
     /* set new elements to NULL */
     for (i = vec->len; i < newsz; i++)
         vec->data[i] = NULL;
     return true;
 }